language: node_js
node_js:
  - "iojs"
  - "7"
  before_script:
  - npm install -g
  - npm install -g create-react-app
deploy:
  provider: s3
  access_key_id: "AKIAJAUTSDISZBU4RXUA"
  secret_access_key: "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"
  bucket: "tesla2"
  skip_cleanup: true
  region: "ap-southeast-2"
  acl: public_read
  local_dir: build