language: node_js
node_js:
  - "iojs"
  - "6.4.1"
deploy:
  provider: s3
  access_key_id: "AKIAJAUTSDISZBU4RXUA"
  secret_access_key: "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"
  bucket: "tesla2"